name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bump version
        id: version
        run: |
          # 获取当前版本
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          # 将版本号分割为主版本号、次版本号和修订号
          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
          # 增加修订号
          NEW_PATCH=$((VERSION_PARTS[2] + 1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH"
          # 更新 package.json 中的版本号
          npm version $NEW_VERSION --no-git-tag-version
          # 输出新版本号供后续步骤使用
          echo "::set-output name=new_version::$NEW_VERSION"
          # 提交版本更新
          git add package.json
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
          git push

      - name: Build project
        run: npm run build

      - name: Package applications
        run: |
          mkdir -p dist
          # 为不同平台打包
          npm install -g pkg
          pkg . --targets node18-linux-x64,node18-macos-x64,node18-win-x64 --output dist/cursor-reset

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          name: Release v${{ steps.version.outputs.new_version }}
          draft: false
          prerelease: false
          files: |
            dist/cursor-reset-linux
            dist/cursor-reset-macos
            dist/cursor-reset-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
